version: "3.8"
services:
  backend:
    image: "daviramosuc/springboot-react-fullstack:18.1.2022.21.17.51"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev