version: "3.8"
services:
  backend:
    image: "daviramosuc/springboot-react-fullstack:15.1.2022.17.52.58"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev