version: "3.8"
services:
  backend:
    image: "daviramosuc/springboot-react-fullstack:13.1.2022.15.46.10"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev